# Configuration for Release Drafter: https://github.com/release-drafter/release-drafter
name-template: WinSW v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION

# This repo follows the Semantic Versioning 2.0.0 approach: https://semver.org/
version-template: $MAJOR.$MINOR.$PATCH

template: $CHANGES

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ':rotating_light: Removed'
    label: removed
  - title: ':warning: Deprecated'
    label: deprecated
  - title: ':tada: New features'
    label: new-feature
  - title: ':rocket: Enhancements'
    label: enhancement
  - title: ':bug: Bug fixes'
    label: bug
  - title: ':package: Packaging changes'
    label: packaging
  - title: ':pencil: Documentation updates'
    label: documentation
  # Default label used by Dependabot
  - title: ':arrow_up: Dependency updates'
    label: dependencies
  - title: ':ghost: Maintenance'
    labels: 
      - internal
      - build-flow
  - title: ':vertical_traffic_light: Tests'
    label: tests
exclude-labels:
  - reverted
  - skip-changelog
  - invalid

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
  - search: 'WinSW'
    replace: 'Windows Service Wrapper'
