name: 🐛 Bug report
description: Create a bug report to help us improve
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Summary
      description: Describe the expected and actual behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please clarify how to reporduce the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Configuration
      description: Paste your XML here
      render: xml
  - type: input
    attributes:
      label: WinSW version
    validations:
      required: true
  - type: dropdown
    attributes:
      label: WinSW package type
      options:
        - .NET Framework
        - .NET Core
    validations:
      required: true
  - type: input
    attributes:
      label: Windows version
    validations:
      required: true
  - type: input
    attributes:
      label: Wrapped executable and version
      description: ex. Jenkins 2.222.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible solution
      description: If you have suggestions on a fix for the bug, please describe it here.
