# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 3.0.0-alpha.$(Revision)

trigger:
- v3

pr:
- v3

variables:
- name: Revision
  value: $[counter(3.0.0, 1)]
- name: BuildVersion
  value: 3.0.0
- name: InformationalVersion # do not rename (MSBuild property)
  value: 3.0.0+$(Build.SourceVersion)

jobs:
- job: Build
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      Debug:
        BuildConfiguration: Debug
      Release:
        BuildConfiguration: Release
  steps:
  - task: UseDotNet@2
    displayName: Install .NET SDK
    inputs:
      packageType: sdk
      version: 5.x
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: src\WinSW.sln
      arguments: -c $(BuildConfiguration) -p:Version=$(BuildVersion)
  - script: |
      dotnet publish src\WinSW\WinSW.csproj -c $(BuildConfiguration) -f net5.0 -r win-x64 -p:Version=$(BuildVersion)
    displayName: Build
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: src\WinSW.Tests\WinSW.Tests.csproj
      arguments: -c $(BuildConfiguration) --collect "XPlat Code Coverage" --no-build
  - task: NuGetToolInstaller@1
    displayName: Install Nuget
    inputs:
      checkLatest: true
  - task: NuGetCommand@2
    displayName: Pack
    inputs:
      command: pack
      packagesToPack: WinSW.nuspec
      versioningScheme: byEnvVar
      versionEnvVar: BuildVersion
  - publish: artifacts\publish\WinSW.NET461.exe
    artifact: WinSW.NET461.exe_$(BuildConfiguration)
    displayName: Publish .NET 4.6.1
  - publish: artifacts\publish\WinSW.NETCore.x64.exe
    artifact: WinSW.NETCore.x64.exe_$(BuildConfiguration)
    displayName: Publish .NET Core x64 .exe
  - publish: $(Build.ArtifactStagingDirectory)\WinSW.$(BuildVersion).nupkg
    artifact: WinSW.nupkg_$(BuildConfiguration)
    displayName: Publish Nuget
